
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The target system is: DOS -  - I86
      The host system is: Linux - 6.8.0-63-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags:  
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: -c 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags:  
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: -c 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: -Aa 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: -D__CLASSIC_C__ 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: --target=arm-arm-none-eabi;-mcpu=cortex-m3 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" failed.
      Compiler: wcl 
      Build flags: 
      Id flags: -c;-I__does_not_exist__ 
      
      The output was:
      No such file or directory
      
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1144 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:86 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/watcom/binl64/wcl 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Open Watcom C/C++ x86 16-bit Compile and Link Utility
      Version 2.0 beta Jul  5 2025 17:20:43 (64-bit)
      Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
      Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
      Source code is available under the Sybase Open Watcom Public License.
      See https://github.com/open-watcom/open-watcom-v2#readme for details.
      	wcc CMakeCCompilerId.c 
      Open Watcom C x86 16-bit Optimizing Compiler
      Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
      Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
      Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
      Source code is available under the Sybase Open Watcom Public License.
      See https://github.com/open-watcom/open-watcom-v2#readme for details.
      CMakeCCompilerId.c: 881 lines, included 53, 0 warnings, 0 errors
      	wlink @__wcl_00.lnk
      Open Watcom Linker Version 2.0 beta Jul  5 2025 17:08:45 (64-bit)
      Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
      Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
      Source code is available under the Sybase Open Watcom Public License.
      See https://github.com/open-watcom/open-watcom-v2#readme for details.
      loading object files
      searching libraries
      creating a DOS executable
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is OpenWatcom, found in:
        /home/jeremy/dosbox/XTCHESS/bin/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        Open Watcom C/C++ x86 16-bit Compile and Link Utility
        Version 2.0 beta Jul  5 2025 17:20:43 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        	wcc /nologo.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/nologo.c'
        	wcc /showIncludes.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/showIncludes.c'
        	wcc /c.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/c.c'
        	wcc main.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        main.c: 3 lines, included 55, 1 warnings, 0 errors
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        Open Watcom C/C++ x86 16-bit Compile and Link Utility
        Version 2.0 beta Jul  5 2025 17:20:43 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        	wcc /nologo.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/nologo.c'
        	wcc /showIncludes.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/showIncludes.c'
        	wcc /c.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/c.c'
        	wcc main.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        main.c: 3 lines, included 55, 1 warnings, 0 errors
        
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/jeremy/dosbox/XTCHESS/bin/CMakeFiles/CMakeScratch/TryCompile-19ELQo"
      binary: "/home/jeremy/dosbox/XTCHESS/bin/CMakeFiles/CMakeScratch/TryCompile-19ELQo"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/jeremy/dosbox/XTCHESS/bin/CMakeFiles/CMakeScratch/TryCompile-19ELQo'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 wmake -f Makefile cmTC_8e761/fast
        Open Watcom Make Version 2.0 beta Jul  5 2025 17:09:03 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        	/opt/watcom/binl64/wmake  -f CMakeFiles/cmTC_8e761.dir/build.make -h CMakeFiles/cmTC_8e761.dir/build
        Building C object CMakeFiles/cmTC_8e761.dir/CMakeCCompilerABI.c.obj
        /opt/watcom/binl64/wcl -zq -d+  -I"/opt/watcom/h" -d2 -foCMakeFiles/cmTC_8e761.dir/CMakeCCompilerABI.c.obj -c -cc /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Linking C executable cmTC_8e761.exe
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8e761.dir/link.txt --verbose=1
        /usr/bin/ld option quiet name cmTC_8e761.exe debug all file {CMakeFiles/cmTC_8e761.dir/CMakeCCompilerABI.c.obj} 
        /usr/bin/ld: cannot find option: No such file or directory
        /usr/bin/ld: cannot find quiet: No such file or directory
        /usr/bin/ld: cannot find name: No such file or directory
        /usr/bin/ld: cannot find cmTC_8e761.exe: No such file or directory
        /usr/bin/ld: cannot find debug: No such file or directory
        /usr/bin/ld: cannot find all: No such file or directory
        /usr/bin/ld: cannot find file: No such file or directory
        /usr/bin/ld: cannot find {CMakeFiles/cmTC_8e761.dir/CMakeCCompilerABI.c.obj}: No such file or directory
        Error(E42): Last command making (cmTC_8e761.exe) returned a bad status
        Error(E02): Make execution terminated
        Error(E42): Last command making (cmTC_8e761/fast) returned a bad status
        Error(E02): Make execution terminated
        
      exitCode: 2
...
