
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:7 (project)"
    message: |
      The target system is: DOS -  - I86
      The host system is: Linux - 6.8.0-63-generic - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /opt/watcom/binl64/wcl 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Open Watcom C/C++ x86 16-bit Compile and Link Utility
      Version 2.0 beta Jul  5 2025 17:20:43 (64-bit)
      Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
      Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
      Source code is available under the Sybase Open Watcom Public License.
      See https://github.com/open-watcom/open-watcom-v2#readme for details.
      	wcc CMakeCCompilerId.c 
      Open Watcom C x86 16-bit Optimizing Compiler
      Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
      Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
      Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
      Source code is available under the Sybase Open Watcom Public License.
      See https://github.com/open-watcom/open-watcom-v2#readme for details.
      CMakeCCompilerId.c: 881 lines, included 53, 0 warnings, 0 errors
      	wlink @__wcl_00.lnk
      Open Watcom Linker Version 2.0 beta Jul  5 2025 17:08:45 (64-bit)
      Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
      Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
      Source code is available under the Sybase Open Watcom Public License.
      See https://github.com/open-watcom/open-watcom-v2#readme for details.
      loading object files
      searching libraries
      creating a DOS executable
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is OpenWatcom, found in:
        /home/jeremy/dosbox/XTCHESS/bin/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        Open Watcom C/C++ x86 16-bit Compile and Link Utility
        Version 2.0 beta Jul  5 2025 17:20:43 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        	wcc /nologo.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/nologo.c'
        	wcc /showIncludes.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/showIncludes.c'
        	wcc /c.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/c.c'
        	wcc main.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        main.c: 3 lines, included 55, 1 warnings, 0 errors
        
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:1182 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:247 (CMAKE_DETERMINE_MSVC_SHOWINCLUDES_PREFIX)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:7 (project)"
    message: |
      Detecting C compiler /showIncludes prefix:
        Open Watcom C/C++ x86 16-bit Compile and Link Utility
        Version 2.0 beta Jul  5 2025 17:20:43 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        	wcc /nologo.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/nologo.c'
        	wcc /showIncludes.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/showIncludes.c'
        	wcc /c.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        Error: Compiler returned a bad status compiling '/c.c'
        	wcc main.c 
        Open Watcom C x86 16-bit Optimizing Compiler
        Version 2.0 beta Jul  5 2025 17:12:41 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1984-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        main.c: 3 lines, included 55, 1 warnings, 0 errors
        
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:7 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/home/jeremy/dosbox/XTCHESS/bin/CMakeFiles/CMakeScratch/TryCompile-kLTZY0"
      binary: "/home/jeremy/dosbox/XTCHESS/bin/CMakeFiles/CMakeScratch/TryCompile-kLTZY0"
    cmakeVariables:
      CMAKE_C_FLAGS: "-w3 -bt=dos"
      CMAKE_C_FLAGS_DEBUG: "-d2"
      CMAKE_EXE_LINKER_FLAGS: "opt map system dos"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/home/jeremy/dosbox/XTCHESS/bin/CMakeFiles/CMakeScratch/TryCompile-kLTZY0'
        
        Run Build Command(s): /usr/bin/cmake -E env VERBOSE=1 wmake -f Makefile cmTC_68114/fast
        Open Watcom Make Version 2.0 beta Jul  5 2025 17:09:03 (64-bit)
        Copyright (c) 2002-2025 The Open Watcom Contributors. All Rights Reserved.
        Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
        Source code is available under the Sybase Open Watcom Public License.
        See https://github.com/open-watcom/open-watcom-v2#readme for details.
        	/opt/watcom/binl64/wmake  -f CMakeFiles/cmTC_68114.dir/build.make -h CMakeFiles/cmTC_68114.dir/build
        Building C object CMakeFiles/cmTC_68114.dir/CMakeCCompilerABI.c.obj
        /opt/watcom/binl64/wcl -zq -d+  -I"/opt/watcom/h" -w3 -bt=dos -d2 -foCMakeFiles/cmTC_68114.dir/CMakeCCompilerABI.c.obj -c -cc /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Linking C executable cmTC_68114.exe
        /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_68114.dir/link.txt --verbose=1
        /opt/watcom/binl64/wlink option quiet name cmTC_68114.exe opt map system dos  debug all file {CMakeFiles/cmTC_68114.dir/CMakeCCompilerABI.c.obj} 
        
      exitCode: 0
...
